spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: fitnessactivity

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 10
      delivery-timeout-ms: 120000
      request-timeout-ms: 30000
      enable-idempotence: true
      max-in-flight-requests-per-connection: 1

kafka:
  topic:
    name: activity-events

server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true